### ISSUE TITLE
Docuseal Deploy Fail on Railway.app

### ISSUE THREAD

**Issue by soucannabis** [docusealco/docuseal-railway#2]
Deployment error, something related to Puma.

deploy log...

Puma starting in single mode...
* Puma version: 6.4.3 (ruby 3.3.4-p94) ("The Eagle of Durango")
* Min threads: 15
* Max threads: 15
* Environment: production
* PID: 1

WARNING: Nokogiri was built against libxml version 2.12.9, but has dynamically loaded 2.12.7
! Unable to load application: NoMethodError: undefined method `has_many_inversing=' for class ActiveRecord::Base
bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
/usr/local/bundle/gems/activerecord-7.2.1.1/lib/active_record/dynamic_matchers.rb:22:in method_missing': undefined method has_many_inversing=' for class ActiveRecord::Base (NoMethodError)
 from /usr/local/bundle/gems/activerecord-7.2.1.1/lib/active_record/railtie.rb:271:in `block (3 levels) in <class:Railtie>'
 from /usr/local/bundle/gems/activerecord-7.2.1.1/lib/active_record/railtie.rb:261:in `each'
 from /usr/local/bundle/gems/activerecord-7.2.1.1/lib/active_record/railtie.rb:261:in `block (2 levels) in <class:Railtie>'

**Comment by nickqweaver** [comment]
I am having the same problem

**Comment by AlexBTurchyn** [comment]
@nickqweaver We recently updated the deployment process. Could you please try again?

**Comment by nickqweaver** [comment]
@AlexBTurchyn Confirmed it works now. Thanks!

**Comment by AlexBTurchyn** [comment]
@soucannabis Could you please also try again?
